### ISSUE TITLE
Feature request: ability to reveal currently playing track in the library

### ISSUE THREAD

**Issue by YurySolovyov** [martpie/museeks#417]
On large libraries, it is easy to get lost and spot the playing indicator

**Comment by igorer88** [comment]
Something I like from Rhythmbox is the ability to mark current playing song
by positioning it and mark it as  selected in the center of the list.

El 9 mar. 2018 6:52 AM, "Yury" <notifications@github.com> escribió:

On large libraries, it is easy to get lost and spot the playing indicator

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KeitIG/museeks/issues/417>, or mute the thread

**Comment by martpie** [comment]
I am thinking about implementing this one, but I am struggling for the design part. A shortcut could do the trick, but a button/action/something would be really helpful too for people who are not keyboard-only.

**Comment by YurySolovyov** [comment]
Options (not mutually exclusive):
- Context menu item (Kinda like in Chrome dev tools)
- An icon/button in header (it is pretty crowded already tho)
- Make track name clickable

**Comment by ldexterldesign** [comment]
When I created https://github.com/martpie/museeks/issues/519 it was related to this issue but when @martpie mentions a shortcut to currently playing track I realise they are distinct issues...

When navigating between views (i.e. libraries, playlists, settings) the view state/position should always persist in case the user is jumping between views to complete a task

Skipping to currently playing track is a separate useful thing

Sincerely
