### ISSUE TITLE
[Request] Add PPA for Ubuntu

### ISSUE THREAD

**Issue by tonywei92** [martpie/museeks#535]
So far the best MP3 player can handle 3000+ mp3 files very fast.
Please add this app to PPA, So Ubuntu users can get updates easily.

https://launchpad.net/ubuntu/+ppas

**Comment by martpie** [comment]
Hello there 👋 

I have no plan to add support for PPA, not because I don't care about Ubuntu users, but because Linux packages build is already hard, and Linux packages distribution is even harder: now it's Ubuntu, tomorrow it will be Debian, Fedora, Arch, Elementary... I just don't have time to maintain all this.

Like brew, if someone wants a PPA for Museeks, it will have to be community-based.

If there is a lot of traction, we might want to try to find a way to automate this, but as long as it will be manual, it's just not worth it.

I hope you understand :)
