### ISSUE TITLE
Edit more id3 tags (art. date, etc)

### ISSUE THREAD

**Issue by kris20030705** [martpie/museeks#732]
Hello dev!
i know this is minimal music player but please work in editing tags..
there is possible to edit tags but only artist,song,ablum & genre..
please add more option like: album art, lyrics. date.etc..
hope to see asap..

**Comment by igorer88** [comment]
@martpie I would like to collaborate with that. Editing the tags on the file. There is a limitation? Or it wasn't  on the scope yet? Working with the lyrics would be fun too. Let me know where I can help.

**Comment by martpie** [comment]
Thank you for willing to contribute! Here are some code pointers:

- Please read the README.md for the setup guide
- UI:
  - Editing more fields in the DB should be quite straightforward (and I just fixed it with the Tauri version of Museeks):
  - [`ViewTrackDetails.tsx`]([ViewTrackDetails.tsx](https://github.com/martpie/museeks/blob/master/src/views/ViewTrackDetails.tsx)) holds the form 
  - [`useLibraryStore`](https://github.com/martpie/museeks/blob/master/src/stores/useLibraryStore.ts#L176-L211) handles the back-end submission logic
  - [`database.ts`](https://github.com/martpie/museeks/blob/master/src/lib/database.ts#L23-L27) is a small wrapper around IPC communication (communication between the UI and the Back-End
- Back-end:
  - [`database.rs`] holds the logic updating the track. Right now it only overrides the database records, but does not set the ID3 tags.
  - In order to do so, you may need to leverage the rust library I use to scan the ID3 tags: [`lofty`](https://docs.rs/lofty/latest/lofty/). I believe they have methods to write ID3 tags.

I did not want to do it because it's a tricky feature and I really don't want Museeks for being responsible for destroying someone's library (hence the current "read-only" aspect of Museeks).

On a more UX side: we should probably make this ID3 write optional (and disabled by default). You can use a checkbox to ask the users what they want.

Good luck, and if you need any help, please ping me!

**Comment by igorer88** [comment]
Nice @martpie I'm currently working on the form with the new fields in the Track type leaving outside _id.

Fixed a  minor bug on artists description hehe
<img width="613" alt="imagen" src="https://github.com/user-attachments/assets/2bc31940-2e01-4ba0-a3b6-d56cd2d2237b">

As far I have some doubts, thou.

1.   Inline inputs
  -   As track and disk are attributes that has 2 fields (on & of) , there should be two inputs side by side, I tried to do it with the existing input component but It's design for block type form. How should we proceed? Should I make another component for these inputs? If so, any name suggestions?
 
2. Read only or disabled inputs?
- For the fields of duration and path that cannot be change should I use read only or disabled attributes?

<img width="613" alt="imagen" src="https://github.com/user-attachments/assets/b8e81dad-68a7-469c-a1a6-b471e66b4d1c">

**Comment by martpie** [comment]
For Inline inputs, you can probably use the Flexbox component (in sec/elements), and set a gap of 8 or something.

For read-only fields, I don't really know, my intuition tells me they should probably not be shown at all.

**Comment by igorer88** [comment]
@martpie ok ok. Thanks.

 I think that it's nice to know the location of the file, there are some cases that some files could be duplicated and it would help the user to know which one to remove and which one to leave in the library.

**Comment by igorer88** [comment]
@martpie there is some issue with album art. While there is an Id3 Tag , it doesn't show in Museeks. 
It should be something specific about that track metadata, and probably could be fix by updating that tag. 

But got me wondering, from where does Museeks fetches it?
As for now , it isn't in the Track's type. It would be nice to add it so it can be updated by the form. 
I believe that lofty handles it in another type with it's own methods, but I need to further read the docs.

<img width="930" alt="imagen" src="https://github.com/user-attachments/assets/08baceae-dadf-4f17-82cd-57740d5d9495">

<img width="930" alt="imagen" src="https://github.com/user-attachments/assets/e6892d6e-cf90-4fd6-b1e9-9ab42440f111">

**Comment by martpie** [comment]
For the cover, you can see how Museeks get it from the `get_cover` function. It is invoked on track change as we should not store images in the database (too slow).

Basically, if no ID3 cover exists, we check the filesystem to see if there is a jpg/png in the same directory as the track path.

https://github.com/martpie/museeks/blob/master/src-tauri/src/plugins/cover.rs

TBH, I would rather not touch the cover as storing it as ID3 can increase the size of the file. 

What could be done though is telling users to add a `cover.jpg` in their directory, or make the form store the file there, if you feel brave enough.

**Comment by martpie** [comment]
More generally, don't hesitate to split your work into multopme PRs/or well defined commits (one for the form + fields update, one for writing ID3, one for the covers, etc). ;)

**Comment by igorer88** [comment]
Sorry for the late reply. I figure it out what was the issue with that song in particular:
- The cover is present on the Other tag, while Museeks only searches on the Front Cover tag.
We could stick to the Front Cover, however as other music players as Apple Music seems to grab any picture from any tag, we could try to do something like that.

About storing the cover on the tag, well that's the standard way, it means that it would work on every other music player.
We could limit the file to a certain size and use only one type, 
I had always use 500x500 for all my files. A JPG image like that only adds literally a couple of Kb, it's imperceptible.

**Comment by igorer88** [comment]
@martpie I'm doing the first PR, I just need to fix conflicts from the current version.

**Comment by igorer88** [comment]
@martpie I think I've broke it xD
How can I reset de DB? It skips the tracks.  Because it thinks that they are already imported.

<img width="891" alt="imagen" src="https://github.com/user-attachments/assets/2f8ca495-ca9d-498f-a3d9-67f20d455a08">

<img width="891" alt="imagen" src="https://github.com/user-attachments/assets/70fa1012-7488-4f03-b112-a63c9433f637">

**Comment by martpie** [comment]
Let's move the discussion to the PR :)
