### ISSUE TITLE
Compile Sass on the fly

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#87]
Related Issue #16 
Related PR #83

Instead of using webpack, that'd be great to compile styles on the fly (we may want to implement custom/community themes in the future).

There are a few questions to answer:
- Where do we write the compiled Sass (file, DOM ...) ?
- We might need to split the main styles and the light theme

**Comment by puranjayjain** [comment]
we can use nodesass like atom does to compile sass on the fly/on demand.
Split themes that'd be really awesome.
Structure some sort of api around the important elements and document it:
e.g we can assign ids to specific components e.g play button, playlist, etc.
So that the theme designer can use almost anything to style the frontend.(lot of options nowadays e.g react, polymer, bootstrap, etc. more options more freedom will be a good factor).

**Comment by KeitIG** [comment]
This issue is the next to do. The goal is not do developp now a complete and automated system for themes (that will come later), but to have a nice base to start with.

- There is a theme by default (the light one)
- Themes are just overrides of the light theme
- Themes when selected in settings, are compiled with `node-sass` and put in the DOM or in a file called by a link (http://stackoverflow.com/questions/34296274/compile-css-on-the-fly-with-node-sass)
- Themes are selected with a `select` and not a `checkbox`
- There is a scan of existing themes in a folder or sth
- Bonus: create a base theme easily editable with variables, so everyone can compile a theme by changing a few lines, and can submit it with a PR

**Comment by KeitIG** [comment]
About what you said @puranjayjain (classes, components...), honestly, a lot of node are well named, and by enabling the dev mode, it's easy to inspect the DOM. (+ a lot of Bootstrap class are used)

But the important indications will be mentioned in a README.

**Comment by YurySolovyov** [comment]
[electron-compile](https://github.com/electron/electron-compile) seems like an option to  consider

**Comment by martpie** [comment]
This issue will become obsolete after the stylesheets refactoring. Its main purpose what for theming, but switching to CSS variables will solve this problem.

**Comment by puranjayjain** [comment]
Agreed, after changing to css variables it seems we might not required sass compilation at all. Nice work 👍
